services:
  postgres:
    image: postgres:16-alpine
    container_name: ferretodo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ferretodo
      POSTGRES_PASSWORD: ferretodo
      POSTGRES_DB: ferretodo
    ports:
      - "5432:5432"
    volumes:
      - ferretodo_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ferretodo"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ferretodo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ferretodo_redis:/data

  mailhog:
    image: mailhog/mailhog
    container_name: ferretodo-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  ferretodo_pg:
  ferretodo_redis:
